name: Container build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  schedule:
    - cron: '5 5 * * *'

env:
  CONTAINER_IMAGE_NAME: raw-photo-tools
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ github.repository_owner }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  container-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to ${{ env.CONTAINER_REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USER }}
        password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

    - name: Prepare
      id: tags
      run: |
        case "${GITHUB_REF}" in
          refs/tags/*)  VERSION="${GITHUB_REF#refs/tags/}" ;;
          refs/heads/*) VERSION=$(echo "${GITHUB_REF#refs/heads/}" | sed -r 's#/+#-#g') ;;
          refs/pull/*)  VERSION="pr-${{ github.event.number }}" ;;
          *)            VERSION="sha-${GITHUB_SHA::8}" ;;
        esac
        echo "::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        echo "::set-output name=VERSION::${VERSION}"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images:
          ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          latest
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.version=${{ steps.tags.outputs.VERSION }}
          org.opencontainers.image.created=${{ steps.tags.outputs.BUILD_DATE }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      id: build-push-action
      with:
        context: ./
        load: true
        tags: ${{ steps.meta.outputs.tags }}

    # - name: Trivy Scan Image
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ steps.meta.outputs.version }}
    #     format: table
    #     exit-code: 1
    #     ignore-unfixed: true
    #     vuln-type: os,library
    #     severity: CRITICAL
    #     cache-dir: .trivy

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      if: always()
      with:
        image-ref: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ steps.meta.outputs.version }}
        format: template
        template: "@/contrib/sarif.tpl"
        output: trivy-results.sarif
        severity: CRITICAL,HIGH
        cache-dir: .trivy

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: always()
      with:
        sarif_file: "trivy-results.sarif"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.CONTAINER_IMAGE_NAME }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create Release Notes
      uses: actions/github-script@v5
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: "${{ github.ref }}",
            generate_release_notes: true
          });
