name: df-check

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/virt-check.yml

jobs:
  check-mac:
    runs-on: macos-latest
    steps:
      - name: df
        shell: bash
        run: |
          set -x
          # df -h /
          # brew remove --force $(brew list --formula)
          # IFS=$'\n' read -rd '' -a args < <(brew list --formula)
          # echo "${args[@]}"
          # brew remove --force "${args[@]}"
          brew install bash
          /usr/local/bin/bash --version
          /usr/local/bin/bash << \EOF
          readarray -t args < <(brew list --formula) ;
          echo "${args[@]}" ;
          brew remove --force "${args[@]}" ;
          EOF
          # df -h /
          # brew remove --force $(brew list --casks)
          # sudo du -sh /* 2>/dev/null || true
          # df -h /
          # rm -rf /Users/runner/hostedtoolcache/
          # df -h /
          # brew cleanup -s
          # df -h /
          # rm -rf "$(brew --cache)"
          # df -h /
          # brew list --casks
          # set +x
          # brew install findutils
          # brew list --formula | xargs  -P8 -I {} \
          #   sh -c "brew info {} | egrep '[0-9]* files, ' | sed 's/^.*[0-9]* files, \(.*\)).*$/{} \1/'" | \
          #   sort -h -r -k2 - | column -t | grep MB | sort -k2 -g
          brew install dust hudochenkov/sshpass/sshpass
          dust -r -b -n 60 /
          VirtualBox --help
          brew upgrade virtualbox 
          VirtualBox --help
          brew update &> /dev/null
          VirtualBox --help
          brew upgrade virtualbox
          brew install virtualbox


      - name: Install packages - SKIP
        if: ${{ env.skip == 'true' }}
        run: |
          set -x
          [[ -f /usr/local/bin/2to3 ]] && rm /usr/local/bin/2to3
          brew update > /dev/null
          brew install bash coreutils gnu-sed packer vagrant
          MATRIX_STAGE=${{ matrix.stage }}
          if [[ "${MATRIX_STAGE}" =~ "libvirt" ]]; then
            brew install qemu xorriso
          fi
          if [[ "${MATRIX_STAGE}" =~ "virtualbox" ]]; then
            brew install virtualbox
            brew install --cask virtualbox-extension-pack
          fi
          pip3 install ansible==4.5.0 pywinrm==0.4.2
          ansible-galaxy collection install ansible.windows:=1.7.2 chocolatey.chocolatey:=1.1.0
          echo "/usr/local/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin" >> "${GITHUB_PATH}"
