name: gh-secrets

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/gh-secrets.yml

jobs:
  gh-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: gh-secrets
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -euxo pipefail
          which gh
          gh --version
          gh secret set test_delete --body "123456"
