name: mytest

on:
  workflow_dispatch:
    inputs:
      version:
        description: Action
        default: create, delete
        required: true
  push:
    branches:
      - master
    paths:
      - .github/workflows/mytest.yml
      - docs/**
      - create-*.sh
      - delete-*.sh
      - docker-create-*.sh
      - docker-delete-*.sh

jobs:
  create:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.version, 'create') || ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) }}
    steps:
      - name: Test - create
        # if: ${{ contains(github.event.inputs.version, 'create') || ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) }}
        run: |
          set -x
          echo ${{ github.event.inputs.version }}
          exit 0
          #exit 1

  delete:
    runs-on: ubuntu-latest
    needs: create
    if: ${{ ( contains(github.event.inputs.version, 'delete') && success() ) || ( github.event_name == 'push' && github.ref == 'refs/heads/master' && always() ) }}
    steps:
      - name: Test - delete
        run: |
          set -x
          echo ${{ github.event.inputs.version }}
          exit 0
