name: mytest

on:
  workflow_dispatch:
    inputs:
      version:
        description: Action
        default: create, delete
        required: true
      cluster_name:
        description: Cluster Name
        default: kube2
        required: false
  push:
    branches:
      - master
    paths:
      - .github/workflows/mytest.yml
      - docs/**
      - create-*.sh
      - delete-*.sh
      - docker-create-*.sh
      - docker-delete-*.sh

env:
  CLUSTER_NAME: kube3

concurrency: test123

jobs:
  create:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.version, 'create') || ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) }}
    steps:
      - name: Replace CLUSTER_NAME variable if defined manually
        if: ${{ github.event.inputs.cluster_name }}
        run: |
          echo CLUSTER_NAME="${{ github.event.inputs.cluster_name }}" >> $GITHUB_ENV

      - name: Test - create
        run: |
          set -x
          echo "version: ${{ github.event.inputs.version }}"
          echo "CLUSTER_NAME: ${CLUSTER_NAME}"
          export COMPOSE_INTERACTIVE_NO_CLI=1
          docker run -i --rm \
            -v "${PWD}:/mnt" \
            -w /mnt \
            ubuntu \
            bash -eu -c " \
              date ;\
              ls --color -lh /
            "
          #sleep 300
          exit 0
          #exit 1

  delete:
    runs-on: ubuntu-latest
    needs: create
    # PR
    if: ${{ contains(github.event.inputs.version, 'delete') || ( github.event_name == 'push' && github.ref == 'refs/heads/master' && always() ) }}
    steps:
      - name: Test - delete
        run: |
          set -x
          echo ${{ github.event.inputs.version }}
          exit 0
