name: build

on:
  workflow_dispatch:
    inputs:
      build:
        description: Build
        default: my_windows-10-enterprise-x64-eval-libvirt
        required: false
      PACKER_LOG:
        description: PACKER_LOG
        default: 0
        required: false
      ANSIBLE_DEBUG:
        description: ANSIBLE_DEBUG
        default: false
        required: false
      VAGRANT_LOG:
        description: VAGRANT_LOG
        default: warn
        required: false
      build_release_upload:
        description: Upload release to Vagrant Cloud
        default: false
        required: false
  # push:
  #   paths:
  #     - .github/workflows/packer-templates.yml

jobs:
  build-boxes:
    name: "*"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stage:
          - my_ubuntu-20.04-server-amd64-libvirt
          - my_windows-10-enterprise-x64-eval-libvirt
          - ubuntu-16.04-server-amd64-libvirt
          - ubuntu-18.04-desktop-amd64-libvirt
          - ubuntu-18.04-server-amd64-libvirt
          - ubuntu-20.04-desktop-amd64-libvirt
          - ubuntu-20.04-server-amd64-libvirt
          - windows-10-enterprise-x64-eval-libvirt
          - windows-server-2012_r2-standard-x64-eval-libvirt
          - windows-server-2016-standard-x64-eval-libvirt
          - windows-server-2019-standard-x64-eval-libvirt
          - my_ubuntu-20.04-server-amd64-virtualbox
          - my_windows-10-enterprise-x64-eval-virtualbox
          - ubuntu-16.04-server-amd64-virtualbox
          - ubuntu-18.04-desktop-amd64-virtualbox
          - ubuntu-18.04-server-amd64-virtualbox
          - ubuntu-20.04-desktop-amd64-virtualbox
          - ubuntu-20.04-server-amd64-virtualbox
          - windows-10-enterprise-x64-eval-virtualbox
          - windows-server-2012_r2-standard-x64-eval-virtualbox
          - windows-server-2016-standard-x64-eval-virtualbox
          - windows-server-2019-standard-x64-eval-virtualbox

    steps:
      - name: Skip test
        if: github.event_name != 'schedule' || ! contains(matrix.stage, github.event.inputs.build)
        run: |
          set -x
          echo "skip=true ${{ matrix.stage }} | ${{ github.event.inputs.build }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: env.skip != 'true'
        with:
          submodules: true

      - name: Install packages
        if: env.skip != 'true'
        run: |
          set -x
          echo "${{ matrix.stage }}"

      - name: Set environment variables from payload
        if: env.skip != 'true' && ( github.event_name == 'repository_dispatch' && github.event.client_payload )
        run: |
          echo "${{ matrix.stage }}"

      - name: Build image
        if: env.skip != 'true'
        run: |
          echo ${{ matrix.stage }}

      - name: Check the created box image
        if: env.skip != 'true' && contains( matrix.stage, 'virtualbox' )
        run: |
          echo ${{ matrix.stage }}

      - name: Upload box to Vagrant Cloud
        if: env.skip != 'true' && ( github.event_name == 'schedule' || ( github.event_name == 'repository_dispatch' && github.event.action == 'build_release_upload' ) )
        env:
          BOX_VERSION: ${{ env.BOX_VERSION }}
        run: |
          echo ${{ matrix.stage }}

  clean_check_versions:
    needs: build-boxes
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Remove old versions
        run: |
          echo "xxxx"
